### ISSUE TITLE
Newsletter members or members ?

### ISSUE THREAD

**Issue by sfx12** [numero2/contao-brevo-member-sync#1]
Ich weiss nicht ob das hierher gehört, aber werden Mitglieder oder newsletter Abonennten synchronisiert ? Letzteres würde mehr Sinn machen :-) Vielen dank für Ihre Rückantwort.
LG SfX

**Comment by michb** [comment]
Es werden, so wie es in der README steht, die Mitglieder synchronisiert, über die Module "Registrierung" und "Persönliche Daten".
