### ISSUE TITLE
Feature Request. Sync from Backend

### ISSUE THREAD

**Issue by ThomasKettner** [numero2/contao-brevo-member-sync#3]
Is there a chance of enhancing the functionality to start the sync from the backend, for example when saving or by button?

Or can we possibly add this in the eventListener?

**Comment by michb** [comment]
The needed data and credentials for a sync to brevo is only stored in the corresponding frontend modules. Therefore we cannot start a sync from the backend.

Which event listener do you mean?

**Comment by michb** [comment]
We added configuration to the member groups. With this data we can sync the members after each change. Added with 11b05aace6532e1753c9915f4382716af4b088aa.
